export const markerData = [
  {
    position: { lat: 34.8791806, lng: -111.8265049 },
    title: "Boyanton Pass",
    price: "123k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "Arizona",
  },
  {
    position: { lat: 38.8665433, lng: 86.1956316 },
    title: "Airport Mesa",
    price: "223k",
    img: "/next.svg",
    state: "California",
  },
  {
    position: { lat: 34.832149, lng: -111.7695277 },
    title: "Chapel of the Holy Cross",
    price: "444k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "Krasnoyarsk Krai",
  },
  {
    position: { lat: 34.823736, lng: -111.8001857 },
    title: "Red Rock Crossing",
    price: "555k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "California",
  },
  {
    position: { lat: 34.800326, lng: -111.7665047 },
    title: "Bell Rock",
    price: "666k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "Arizona",
  },
  {
    position: { lat: 11.800326, lng: -140.7665047 },
    title: "Bell Rock",
    price: "666k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "Arizona",
  },
  {
    position: { lat: 30.788872, lng: -82.019038 },
    title: "Bell Rock1",
    price: "666k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "florida",
  },
  {
    position: { lat: 30.788872, lng: -83.019038 },
    title: "Bell Rock3",
    price: "66633k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "florida",
  },
  {
    position: { lat: 30.800326, lng: -81.7665047 },
    title: "Bell Rock2",
    price: "616k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "florida",
  },
  {
    position: { lat: 28.800326, lng: -81.7665047 },
    title: "Bell Rock3",
    price: "666k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "florida",
  },
  {
    position: { lat: 27.800326, lng: -82.7665047 },
    title: "Bell Rock4",
    price: "666k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "florida",
  },
  {
    position: { lat: 29.800326, lng: -83.7665047 },
    title: "Bell Rock443",
    price: "666k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "florida",
  },
  {
    position: { lat: 29.820326, lng: -83.8165047 },
    title: "Bell Rock44",
    price: "666k",
    img: "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png",
    state: "florida",
  },
];
